import { Link, useRouterState } from '@tanstack/react-router';
import { useEffect, useState, type ReactNode } from 'react';
import { useCms, photo, type Item } from '@/lib/cms';
import { Button, Icon, Modal, Picture } from './controls';
export const navigation=[['Home','/'],['About','/about'],['Products','/products'],['Capabilities','/capabilities'],['Process','/process'],['Quality','/quality'],['Gallery','/gallery'],['Contact','/contact']] as const;
export function Brand(){const {data}=useCms();return <Link to="/" className="brand" aria-label="MM Thread home"><span className="brand-mark"><Icon name="thread"/></span><div><div className="brand-name">{data.settings.logo}</div><div className="brand-caption">Thread & Textile Solutions</div></div></Link>;}
export function SiteShell({children}:{children:ReactNode}){
 const {data}=useCms();const path=useRouterState({select:s=>s.location.pathname});const [menu,setMenu]=useState(false);const [top,setTop]=useState(false);
 useEffect(()=>{setMenu(false);},[path]);useEffect(()=>{if(path==='/'){document.title=data.settings.seoTitle;document.querySelector('meta[name="description"]')?.setAttribute('content',data.settings.seoDescription);}},[path,data.settings.seoTitle,data.settings.seoDescription]);useEffect(()=>{const listen=()=>setTop(window.scrollY>600);window.addEventListener('scroll',listen,{passive:true});return()=>window.removeEventListener('scroll',listen);},[]);
 return <><header className="navbar"><div className="container nav-inner"><Brand/><nav aria-label="Main navigation" className="desktop-nav">{navigation.map(([name,to])=><Link key={to} to={to} className={path===to?'active':''} aria-current={path===to?'page':undefined}>{name.toUpperCase()}</Link>)}</nav><Link to="/contact" className="btn btn-primary nav-enquiry">Enquire Now <Icon name="arrow"/></Link><Button variant="text" className="mobile-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu}><Icon name={menu?'close':'menu'}/></Button></div>{menu&&<nav className="mobile-nav" aria-label="Mobile navigation">{navigation.map(([name,to])=><Link key={to} to={to} onClick={()=>setMenu(false)} aria-current={path===to?'page':undefined}>{name}</Link>)}</nav>}</header><main className={path==='/'?'home-premium':undefined}>{children}</main><Footer/><a className="floating-contact" href={`https://wa.me/${data.contact.whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noreferrer" aria-label="Contact MM Thread on WhatsApp" title="WhatsApp"><Icon name="chat"/></a>{top&&<Button variant="text" className="back-top" aria-label="Back to top" title="Back to top" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><Icon name="up"/></Button>}</>;
}
export function Footer(){const {data}=useCms();return <footer className="footer"><div className="container footer-grid"><div><Brand/><p>{data.settings.footer}</p><p>Kolhapur, Maharashtra · India</p>{data.settings.social&&<div className="footer-links">{data.settings.social.split(/\n/).filter(url=>/^https:\/\//.test(url.trim())).map((url,i)=><a key={url} href={url.trim()} target="_blank" rel="noreferrer">Social profile {i+1} ↗</a>)}</div>}</div><div><h4>Quick Links</h4><div className="footer-links">{navigation.slice(0,4).map(([n,to])=><Link to={to} key={to}>{n}</Link>)}<Link to="/gallery">Gallery</Link></div></div><div><h4>Our Products</h4><div className="footer-links">{data.products.filter(p=>p.visible).slice(0,5).map(p=><Link to="/products" key={p.id}>{p.title}</Link>)}</div></div><div><h4>Business</h4><div className="footer-links"><Link to="/process">Our Process</Link><Link to="/quality">Quality Assurance</Link><Link to="/about">Our Approach</Link><Link to="/contact">Business Enquiry</Link><Link to="/admin/login" className="footer-admin">Admin Login ↗</Link></div></div><div><h4>Get in Touch</h4><div className="footer-contact"><div><Icon name="pin"/><span>{data.contact.address}</span></div><a href={`tel:${data.contact.phone.replace(/\s/g,'')}`}><Icon name="phone"/>{data.contact.phone}</a><a href={`mailto:${data.contact.email}`}><Icon name="mail"/>{data.contact.email}</a></div></div></div><div className="container footer-bottom"><span>© 2026 MM Thread. All rights reserved.</span><span className="credit">Designed and development by SOSynch Ai Tech</span><Link to="/admin/login">Admin Login</Link></div></footer>;}
export function Intro({title,description,eyebrow}:{title:string;description:string;eyebrow:string}){
 const {data}=useCms();
 const banners:Record<string,{image:string;alt:string}>={
  About:{image:data.about.image,alt:'Textile industry photography — illustrative, not a verified MM Thread facility'},
  Products:{image:photo('products',4),alt:'Colourful thread cones — illustrative B2B thread collection'},
  Capabilities:{image:photo('manufacturing',1),alt:'Fabric weaving looms — illustrative textile manufacturing'},
  Process:{image:photo('manufacturing',3),alt:'Fabric finishing rollers — illustrative textile processing'},
  Quality:{image:photo('manufacturing',4),alt:'Fabric inspection machine — illustrative textile quality control'},
  Gallery:{image:photo('manufacturing',2),alt:'Garment cutting and sewing workshop — illustrative textile production'},
  Contact:{image:photo('process',5),alt:'Packaged thread cones — illustrative B2B thread supply'},
 };
 const banner=banners[eyebrow]||banners['Products'];
 return <section className="page-intro page-banner">{banner&&<Picture src={banner.image} alt={banner.alt} eager/>}<div className="container reveal"><div className="breadcrumb"><Link to="/">Home</Link><Icon name="chevron"/><span>{eyebrow}</span></div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div></section>;
}
export function SectionHeader({eyebrow,title,description,link,label}:{eyebrow:string;title:string;description?:string;link?:'/about'|'/products'|'/capabilities'|'/process'|'/quality'|'/gallery'|'/contact';label?:string}){return <div className="section-header"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{description&&<p className="section-subtitle">{description}</p>}</div>{link&&<Link to={link} className="btn btn-text">{label||'Explore More'}<Icon name="arrow"/></Link>}</div>;}
export function EnquiryBanner(){return <section className="enquiry-banner"><div className="container enquiry-banner-inner"><div><div className="eyebrow">Let's build a lasting partnership</div><h2>Looking for the Right Thread<br/>for Your Business?</h2><p>Tell us what you need and our team can help you identify the right product or solution.</p></div><Link to="/contact" className="btn btn-primary">Send Enquiry<Icon name="arrow"/></Link></div></section>;}
export function ProductCard({product,onDetails,onEnquire}:{product:Item;onDetails:()=>void;onEnquire:()=>void}){return <article className="product-card"><div className="product-image"><Picture src={product.image} alt={`${product.title} — illustrative product photograph`}/><span className="tag">{product.type||'Thread solutions'}</span></div><div className="product-info"><h3>{product.title}</h3><p>{product.description}</p><div className="product-application">{product.application}</div><div className="product-actions"><Button variant="text" onClick={onDetails}>View Details<Icon name="arrow"/></Button><Button variant="text" className="enquire-link" onClick={onEnquire}>Send Enquiry<Icon name="arrow"/></Button></div></div></article>;}
export function ProductDetail({product,onClose,onEnquire}:{product:Item;onClose:()=>void;onEnquire:()=>void}){return <Modal onClose={onClose} label={product.title}><div className="product-detail"><Picture src={product.image} alt={product.title}/><div className="product-detail-copy"><span className="tag">{product.category} · Demo catalogue</span><h2>{product.title}</h2><p>{product.description}</p><h4>Applications</h4><p>{product.application}</p><h4>Key features</h4><ul className="detail-list">{product.features?.split(',').map(f=><li key={f}>{f.trim()}</li>)}</ul><h4>Available variants</h4><p>{product.variants}</p><h4>Typical industries served</h4><p>{product.industries}</p><Button onClick={onEnquire}>Request Product Information<Icon name="arrow"/></Button><p className="demo-note" >Illustrative specifications. Confirm availability with our team.</p></div></div></Modal>;}
export function EnquiryForm({product='',onSubmitted}:{product?:string;onSubmitted?:()=>void}){
 const {data,setData}=useCms();const [submitted,setSubmitted]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const val=(k:string)=>String(form.get(k)||'').trim();if(val('phone').replace(/\D/g,'').length<10){setError('Please enter a valid phone number with at least 10 digits.');return;}setError('');setBusy(true);const entry={id:crypto.randomUUID(),name:val('name'),company:val('company'),phone:val('phone'),email:val('email'),product:val('product'),requirement:val('requirement'),message:val('message'),date:new Date().toISOString(),status:'New'};setData(old=>({...old,enquiries:[entry,...old.enquiries]}));setSubmitted(true);setBusy(false);onSubmitted?.();}
 return <div className="enquiry-form"><h2>Tell Us What You Need</h2><p className="form-note">Share your requirements. Let's find the right thread for your business.</p>{submitted?<div role="status" className="form-message"><Icon name="check"/> Thank you. Your enquiry has been recorded in this demo.<p className="form-note">It is saved on this device only and has not been sent to MM Thread.</p><Button variant="text" onClick={()=>setSubmitted(false)}>Send another enquiry <Icon name="arrow"/></Button></div>:<form onSubmit={submit}><div className="form-grid"><label>Full Name *<input name="name" required autoComplete="name" placeholder="Your full name"/></label><label>Company Name *<input name="company" required autoComplete="organization" placeholder="Your company"/></label><label>Phone Number *<input name="phone" type="tel" required autoComplete="tel" placeholder="Your phone number"/></label><label>Email *<input name="email" type="email" required autoComplete="email" placeholder="you@company.com"/></label><label>Product Category *<select name="product" required defaultValue={product}><option value="">Select a category</option>{data.categories.filter(c=>c.visible).map(c=><option key={c.id}>{c.title}</option>)}<option>Other / General enquiry</option></select></label><label>Quantity / Requirement *<input name="requirement" required placeholder="e.g. quantity, colour, thread count"/></label><label className="full">Message *<textarea name="message" required placeholder="Tell us about your application and requirements"/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-submit"><Button type="submit" disabled={busy}>{busy?'Recording…':'Submit Enquiry'}<Icon name="arrow"/></Button><span className="demo-note">Demo only. No enquiry is sent to a server.</span></div></form>}</div>;
}
export function EnquiryModal({product,onClose}:{product:string;onClose:()=>void}){return <Modal label="Business enquiry" onClose={onClose}><div className="editor-modal"><EnquiryForm product={product}/></div></Modal>;}
export function AboutBlock(){const {data}=useCms();return <div className="about-layout"><div className="about-visual"><Picture src={data.about.image} alt="Thread and textile industry — illustrative photography, not a verified MM Thread facility" className="main-image"/><Picture src={photo('products',9)} alt="Fine woven textile texture" className="small-image"/><div className="image-caption"><Icon name="thread"/>Every thread. A commitment.</div></div><div className="about-copy"><div className="eyebrow">The MM Thread story</div><h2>{data.about.title}</h2><p>{data.about.description}</p><p>From selecting the right thread to supporting your production needs, our approach is simple: listen closely, focus on quality and build relationships that last.</p><Link to="/about" className="btn btn-text">Discover MM Thread<Icon name="arrow"/></Link><div className="about-footnote"><Icon name="pin"/>Rooted in Kolhapur. Focused on your business.</div></div></div>;}
export function Sustainability(){return <section className="sustainability"><div className="container sustainability-inner"><Icon name="leaf"/><div><h3>Moving Toward Responsible Textile Solutions</h3><p>Responsible material choices, reduced waste, efficient production, better packaging and product longevity are areas for continuous improvement. A thoughtful approach, one thread at a time.</p></div><Link to="/quality" className="btn btn-text">Our Approach<Icon name="arrow"/></Link></div></section>;}
